
services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=m06Ar14u-
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200 
      - 9600:9600 
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 
    expose:
      - "5601" 
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net

networks:
  opensearch-net:

volumes:
  opensearch-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Volumes/ExternalDrive/opensearch'
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Volumes/ExternalDrive/data'