-- vim: set ts=4 expandtab
SET client_min_messages TO WARNING;
-- SET ROLE=:XXXX_admin;

-- DROP SCHEMA IF EXISTS podcast CASCADE CASCADE;
-- CREATE SCHEMA podcast;

SET search_path TO podcast;


/**
 *
 *  Extensions, Functions, and Stored Procedures
 *
 **/
--
-- Function to automate updated of `date_modified` columns so that the application is not responsible for managing that value.
--
CREATE OR REPLACE FUNCTION update_date_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.date_modified = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';


DROP TABLE IF EXISTS struct_type CASCADE;
CREATE TABLE struct_type (
      struct_type_id                                                            INTEGER                                     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , date_created                                                              TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP
    , date_modified                                                             TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP
    , display_order                                                             SMALLINT                                    NOT NULL
    , group_name                                                                TEXT                                        NOT NULL
    , att_pub_ident                                                             TEXT                                        NOT NULL
    , att_value                                                                 TEXT                                        NOT NULL
    , PRIMARY KEY (struct_type_id)
);
CREATE UNIQUE INDEX idx_stuct_type_att_pub_ident                                ON struct_type                              USING btree (group_name, att_pub_ident);


DROP TABLE IF EXISTS ingest CASCADE;
CREATE TABLE ingest (
      ingest_id                                                      			INTEGER                                     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , file_hash                                                                 TEXT                                        NOT NULL           -- hash of the entire file read as a string
	, podcast_uuid																UUID										NOT NULL
	, PRIMARY KEY (podcast_ingest_id)
);
CREATE UNIQUE INDEX idx_podcast_ingest_url_uuid									ON podcast_active   						USING btree (url_uuid);


DROP TABLE IF EXISTS meta_container CASCADE;
CREATE TABLE meta_container (
      meta_container_id                                                      	INTEGER                                     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , container_name                                                            TEXT                                        NOT NULL           -- hash of the entire file read as a string
	, PRIMARY KEY (meta_container_id)
);


DROP TABLE IF EXISTS container_podcast_lnk CASCADE;
CREATE TABLE container_podcast_lnk (
      meta_container_id                                                      	INTEGER                                     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , podcast_id                                                           		TEXT                                        NOT NULL           -- hash of the entire file read as a string
	, PRIMARY KEY (meta_container_id, podcast_id)
);


DROP TABLE IF EXISTS purgatory CASCADE;
CREATE TABLE purgatory (
      purgatory_id                                                      		INTEGER                                     NOT NULL
    , podcast_uuid                                                              UUID                                                   -- to OS
    , date_created                                                              TIMESTAMPTZ                                          DEFAULT CURRENT_TIMESTAMP
    , date_modified                                                             TIMESTAMPTZ                                          DEFAULT CURRENT_TIMESTAMP
    , description_selected                                                      INTEGER                                                         -- 110=Cleaned, 120=ChatGPT
    , readability                                                               INTEGER                                              DEFAULT 0
    , is_explicit                                                               INTEGER                                                         -- 0=False 1=True
    , index_status                                                              INTEGER                                              DEFAULT 310        CHECK(index_status IN (310, 320, 330)) -- 1=AUTO 2=MANUAL 3=EXCLUDED
    , episode_count                                                             INTEGER
    , is_deleted                                                                INTEGER                                              DEFAULT 0   -- 0=False 1=True
    , advanced_popularity                                                       FLOAT                                                DEFAULT 0   -- used for calculating APS
    , reason_for_failure                                                        TEXT                                        NOT NULL
    , file_name                                                                 VARCHAR(45)
    , title_cleaned                                                             VARCHAR(100)                                           -- to OS
    , author                                                                    VARCHAR(100)                                           -- to OS
    , language                                                                  VARCHAR(4)                                             -- to OS
    , description_cleaned                                                       TEXT
    , image_url                                                                 VARCHAR(256)                                           -- to OS
    , podcast_url                                                               VARCHAR(128)                                           -- to OS
    , md5_description                                                           VARCHAR(32)
    , md5_title                                                                 VARCHAR(32)
    , md5_podcast_url                                                           VARCHAR(32)
);


DROP TABLE IF EXISTS error_log CASCADE;
CREATE TABLE error_log (
      file_name                                                                 VARCHAR(45)                                 NOT NULL
    , error                                                                     TEXT                                        NOT NULL
    , stack_trace                                                               TEXT                                        NOT NULL
    , date_created                                                              TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS active CASCADE;
CREATE TABLE active (
      active_id                                                         		INTEGER                                     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , podcast_uuid                                                              UUID                                        NOT NULL        -- to OS
    , date_created                                                              TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP
    , date_modified                                                             TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP
    , description_selected                                                      INTEGER                                     NOT NULL        -- 110=Cleaned, 120=ChatGPT
    , readability                                                               INTEGER                                     NOT NULL DEFAULT 0
    , is_explicit                                                               INTEGER                                     NOT NULL        -- 0=False 1=True
    , index_status                                                              INTEGER                                     NOT NULL DEFAULT 1   CHECK(index_status IN (310, 320, 330)) -- 1=AUTO 2=MANUAL 3=EXCLUDED
    , episode_count                                                             INTEGER                                     NOT NULL
    , is_deleted                                                                INTEGER                                     NOT NULL DEFAULT 0   -- 0=False 1=True
    , advanced_popularity                                                       FLOAT                                       NOT NULL DEFAULT 1   -- used for calculating APS
    , file_name                                                                 VARCHAR(45)                                 NOT NULL
    , title_cleaned                                                             VARCHAR(100)                                NOT NULL        -- to OS
    , title_lemma                                                               VARCHAR(100)                                NOT NULL        -- to OS
    , author                                                                    VARCHAR(100)                                                -- to OS
    , language                                                                  VARCHAR(4)                                  NOT NULL        -- to OS
    , description_cleaned                                                       TEXT                                        NOT NULL
    , description_chatgpt                                                       TEXT
    , description_lemma                                                         TEXT                                        NOT NULL        -- to OS
    , vector                                                        			BYTEA                                       NOT NULL        -- to OS
    , image_url                                                                 VARCHAR(256)                                                -- to OS
    , rss_url                                                               	VARCHAR(128)                                NOT NULL        -- to OS
--    , PRIMARY KEY (podcast_active_id)
) PARTITION BY HASH (DATE_PART('second', TIMEZONE('UTC', date_created)));
CREATE INDEX idx_podcast_active_id   ON podcast_active   USING btree (podcast_active_id);
CREATE UNIQUE INDEX idx_md5_file_name       ON podcast_active   USING btree (file_name);
CREATE UNIQUE INDEX idx_md5_podcast_uuid    ON podcast_active   USING btree (podcast_uuid);
CREATE UNIQUE INDEX idx_md5_podcast_url     ON podcast_active   USING btree (md5_podcast_url);
CREATE TABLE podcast_active_00 PARTITION OF podcast_active FOR VALUES WITH (MODULUS 60, REMAINDER 0);



DROP TABLE IF EXISTS quarantine CASCADE;
CREATE TABLE quarantine (
      quarantine_id                                                             INTEGER                                     NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , podcast_uuid                                                              UUID                                        NOT NULL
    , original_podcast_uuid                                                     UUID                                        NOT NULL
    , duplicate_file_name                                                       VARCHAR(45)                                 NOT NULL
    , date_processed                                                            TIMESTAMPTZ                                 NOT NULL DEFAULT CURRENT_TIMESTAMP
    , PRIMARY KEY (quarantine_id)
);
CREATE UNIQUE INDEX idx_podcast_uuid       ON quarantine    USING btree (podcast_uuid);


DROP TABLE IF EXISTS station CASCADE;
CREATE TABLE station (
      station_uuid                                                              UUID                                                                                    NOT NULL PRIMARY KEY
    , station_name                                                              TEXT                                                                                    NOT NULL
    , call_sign                                                                 TEXT                                                                                    NOT NULL
    , station_id                                                                INTEGER                                                                                 NOT NULL
    , category_id                                                               SMALLINT
    , format_id                                                                 SMALLINT
    , organization_id                                                           SMALLINT
    , band_id                                                                   SMALLINT
    , geo_position                                                              POINT
    , date_acquired                                                             DATE
    , date_disposed                                                             DATE
    , has_jump2go                                                               BOOLEAN
    , is_searchable                                                             BOOLEAN
    , frequency                                                                 TEXT
    , website                                                                   TEXT
    , slug                                                                      TEXT
    , phonetic_name                                                             TEXT
    , slogan                                                                    TEXT
    , description                                                               TEXT
    , date_created                                                              TIMESTAMPTZ
    , date_modified                                                             TIMESTAMPTZ
    , site_slug                                                                 TEXT
    , seo_description                                                           TEXT
    , status                                                                    BOOLEAN
    , is_explicit                                                               BOOLEAN
    , publish_state_id                                                          INTEGER
);


